Document: preload-logger
Title: Debian preload-logger Manual
Author: <insert document author here>
Abstract: This manual describes what preload-logger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/preload-logger/preload-logger.sgml.gz

Format: postscript
Files: /usr/share/doc/preload-logger/preload-logger.ps.gz

Format: text
Files: /usr/share/doc/preload-logger/preload-logger.text.gz

Format: HTML
Index: /usr/share/doc/preload-logger/html/index.html
Files: /usr/share/doc/preload-logger/html/*.html
